# This file is automatically updated when a change is pushed to ghostmonitor/github-config

version: 2

updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
      timezone: Europe/Budapest
    ignore:
      - dependency-name: "github.com/ghostmonitor/gm-go-internal"
        versions: [">4.9.x"]
    open-pull-requests-limit: 15
    target-branch: master

