# This file is automatically updated when a change is pushed to ghostmonitor/github-config

version: 2

updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
      timezone: Europe/Budapest
    open-pull-requests-limit: 1
    target-branch: master

