version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.3
  aws-ecr: circleci/aws-ecr@8.1.2
  slack: circleci/slack@4.10.1

parameters:
  aws-region:
    description: |
      AWS region
    type: string
    default: ${AWS_DEFAULT_REGION}
  docker-registry-root:
    description: AWS ECR repository root
    type: string
    default: ${AWS_ECR_REGISTRY_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

commands:
jobs:
  test:
    docker:
      - image: cimg/aws:2023.04
    resource_class: small
    steps:
      - checkout
      - aws-cli/setup:
          role-arn: ${AWS_ROLE_ARN}
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Run tests
          command: |
            aws ecr get-login-password --region << pipeline.parameters.aws-region >> | docker login -u AWS --password-stdin << pipeline.parameters.docker-registry-root >>
            docker-compose up --exit-code-from test --build
      - slack/notify:
          event: pass
          template: basic_success_1
      - slack/notify:
          event: fail
          template: basic_fail_1

workflows:
  buildAndDeploy:
    jobs:
      - test:
          context:
            - aws-ecr
            - slack
